services:
  - type: web
    name: velos-ai
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: cd /opt/render/project/src && uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: GROQ_API_KEY
        sync: false
